### PR TITLE
Update IntrotoGithubActivity

### PR DESCRIPTION
**Pull request by AmandaMaeWoodward**

### CODE REVIEW

**Comment by Natenicholsonn** [comment]
I think this is the pull request, but I'm not positive. 

One thing I learned about in the GitHub introductory course was that it's a streamlined program to collectively work on group projects. It is also a source that provides open research to other git hub users if the files are made public.

I'm not the quickest learner when it comes to technology, I don't really have comp sci experience. I thought it was kind of tough to navigate the site. I am still having a bit of trouble creating pull requests as well.

**Comment by peng0319** [comment]
I'm not sure about what I did is right for the pull request. One thing I learned from GitHub is that it strikes me as a smart, feature-rich, shared programming/data type platform. I believe it will be a great tool after I master it.

**Comment by Petraliu** [comment]
I also not sure if I am requesting a pull request. When I clicked on the green button "new pull request", it showed "compare..." and I couldn't find any button to go further. 
One thing I learned from Github is we can share our work to public and let other people review and revise it, and make my work better. In the same time, people who see the work can learn something in it.

**Comment by 0liviarockz** [comment]
One thing that I learned was what branching is and the purpose it serves. I am stilll trying to sort out exactly how each of the steps I did in the introduction worked together and I am unsure if I could accurately apply the same steps to a project of my own.

**Comment by LuisGonVill** [comment]
I have learnt a bit in how GitHub handles and how it works. It is a bit more complicated than it seems and using pulling requests and creating branches is not the easiest thing to do. Although it is a good start in learning how to use GitHub in the future.

**Pull request merged**
